### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by phawxby** [karan/atom-terminal#29]
[Enter steps to reproduce below:]

1. Open file
2. CTRL+SHIFT+T

**Atom Version**: 0.182.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [atom-terminal](https://github.com/karan/atom-terminal) package, v0.7.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\z269cjbb\.atom\packages\atom-terminal\lib\atom-terminal.coffee:52

TypeError: undefined is not a function
  at Object.module.exports.open (C:\Users\z269cjbb\.atom\packages\atom-terminal\lib\atom-terminal.coffee:52:32)
  at atom-workspace.<anonymous> (C:\Users\z269cjbb\.atom\packages\atom-terminal\lib\atom-terminal.coffee:45:71)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\z269cjbb\AppData\Local\atom\app-0.182.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\z269cjbb\AppData\Local\atom\app-0.182.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\z269cjbb\AppData\Local\atom\app-0.182.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\z269cjbb\AppData\Local\atom\app-0.182.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\z269cjbb\AppData\Local\atom\app-0.182.0\resources\app\src\window-event-handler.js:176:20)

```

### Commands

```
     -8:08.2 command-palette:toggle (atom-pane.pane.active)
     -8:03.7 core:confirm (atom-text-editor.editor.mini)
  2x -8:03.7 atom-terminal:open (atom-pane.pane.active)
     -3:39.6 window:toggle-dev-tools (atom-pane.pane.active)
     -3:35.3 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -3:30.2 atom-terminal:open (atom-pane.pane.active)
     -3:18.9 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
 36x -3:16.6 core:backspace (atom-text-editor.editor.mini)
     -2:32.3 atom-terminal:open-project-root (div.settings-view.pane-item)
     -2:24.5 atom-terminal:open (div.settings-view.pane-item)
  2x -2:22.0 atom-terminal:open-project-root (div.settings-view.pane-item)
  2x -1:25.3 atom-terminal:open (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "atom-terminal": {}
}
```

### Installed Packages

```coffee
# User
atom-terminal, v0.7.0
open-recent, v2.2.0
remote-ftp, v0.6.1

# Dev
No dev packages
```

![untitled](https://cloud.githubusercontent.com/assets/1090602/6371386/354f60f2-bcf3-11e4-88a7-16e0762e5f11.png)

**Comment by tkw1536** [comment]
Weird, we are doing ``require('path')`` at https://github.com/karan/atom-terminal/blob/master/lib/atom-terminal.coffee#L2 Did path.dirname get removed in the node / io.js api?

**Comment by andya9** [comment]
The bug exists on linux too, version 0.187.0.

**Comment by andya9** [comment]
Thank’you

**Comment by mgcrea** [comment]
[Enter steps to reproduce below:]

1. cmd+shift+p atom terminal open

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-terminal](https://github.com/karan/atom-terminal) package, v0.7.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/olivier/.atom/packages/atom-terminal/lib/atom-terminal.coffee:52

TypeError: undefined is not a function
  at Object.module.exports.open (/Users/olivier/.atom/packages/atom-terminal/lib/atom-terminal.coffee:52:32)
  at atom-workspace.<anonymous> (/Users/olivier/.atom/packages/atom-terminal/lib/atom-terminal.coffee:45:71)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -3:13.9.0 core:move-right (atom-text-editor.editor)
  6x -3:12 core:backspace (atom-text-editor.editor)
     -3:02.3.0 core:move-down (atom-text-editor.editor)
     -3:01.7.0 autocomplete-plus:cancel (atom-text-editor.editor)
     -3:01.2.0 core:move-down (atom-text-editor.editor)
     -3:00.6.0 core:move-left (atom-text-editor.editor)
     -2:13.5.0 core:save (atom-text-editor.editor)
     -1:06.6.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:04.3.0 core:select-all (atom-text-editor.editor.mini)
     -1:02.9.0 core:confirm (atom-text-editor.editor.mini)
     -0:07.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:05.3.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:05.3.0 core:cancel (atom-text-editor.editor.mini)
     -0:04.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini)
     -0:01.0 atom-terminal:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "livereload"
    ]
  },
  "atom-terminal": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.1
atom-terminal, v0.7.0
autocomplete-css, v0.6.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
autocomplete-snippets, v1.2.0
color-picker, v1.7.0
file-icons, v1.5.4
language-arduino, v0.2.1
language-jade, v0.4.0
linter, v0.12.1
linter-jshint, v0.1.2
minimap, v4.7.6
project-manager, v1.15.5
travis-ci-status, v0.13.0

# Dev
No dev packages
```

**Comment by leonweber** [comment]
The latest release does not include the fix. So either install from git or manually update the source code according to https://github.com/karan/atom-terminal/commit/08e7c16dff65d590da081661ea55ed4a811034fc.
