### ISSUE TITLE
Failed to activate the minimap package

### ISSUE THREAD

**Issue by martin0258** [karan/atom-terminal#32]
[Enter steps to reproduce below:]

1. Manually updated Minimap to version 4.5.0
2. Failed to activate the minimap package

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: [atom-terminal](https://github.com/karan/atom-terminal) package, v0.7.0

### Stack Trace

Failed to activate the minimap package

```
At undefined is not a function

TypeError: undefined is not a function
  at Package.module.exports.Package.activateServices (c:\Users\Martin\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:355:117)
  at Package.module.exports.Package.activateNow (c:\Users\Martin\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:243:16)
  at c:\Users\Martin\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:221:30
  at Package.module.exports.Package.measure (c:\Users\Martin\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (c:\Users\Martin\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (c:\Users\Martin\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:465:21)
  at c:\Users\Martin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:226:29
  at exit (c:\Users\Martin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (c:\Users\Martin\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (c:\Users\Martin\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
  4x -0:52.9 core:move-down (atom-text-editor.editor.vim-mode.command-mode)
  4x -0:51.2 core:move-up (atom-text-editor.editor.vim-mode.command-mode)
  4x -0:50.0 core:move-down (atom-text-editor.editor.vim-mode.command-mode)
  4x -0:48.7 core:move-up (atom-text-editor.editor.vim-mode.command-mode)
  4x -0:47.6 core:move-down (atom-text-editor.editor.vim-mode.command-mode)
  4x -0:46.3 core:move-up (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:45.0 core:move-down (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:44.4 core:move-up (atom-text-editor.editor.vim-mode.command-mode)
  3x -0:43.8 core:move-down (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:42.7 core:move-up (atom-text-editor.editor.vim-mode.command-mode)
  3x -0:42.0 core:move-down (atom-text-editor.editor.vim-mode.command-mode)
  3x -0:41.0 core:move-up (atom-text-editor.editor.vim-mode.command-mode)
  3x -0:32.9 core:move-down (atom-text-editor.editor.vim-mode.command-mode)
  5x -0:32.0 core:move-up (atom-text-editor.editor.vim-mode.command-mode)
     -0:25.4 core:move-left (atom-text-editor.editor.vim-mode.command-mode)
  3x -0:25.4 core:move-up (atom-text-editor.editor.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "autocomplete"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.0
minimap, v4.5.0
script, v2.18.0
vim-mode, v0.37.0

# Dev
No dev packages
```

**Comment by tkw1536** [comment]
@martin0258 The error message is "Failed to activate the minimap package". Why is this on the atom-terminal package tracker?
