### ISSUE TITLE
Uncaught Error: Cannot find module './minimap-quick-settings-view'

### ISSUE THREAD

**Issue by martin0258** [karan/atom-terminal#33]
[Enter steps to reproduce below:]

1. Click the gear icon of [minimap](https://atom.io/packages/minimap) package.
2. The error appeared.

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: [atom-terminal](https://github.com/karan/atom-terminal) package, v0.7.0

### Stack Trace

Uncaught Error: Cannot find module './minimap-quick-settings-view'

```
At module.js:353

Error: Cannot find module './minimap-quick-settings-view'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (C:\Users\Martin\AppData\Local\atom\app-0.187.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at HTMLDivElement.<anonymous> (C:\Users\Martin\.atom\packages\minimap\lib\minimap-element.coffee:175:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "autocomplete"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.0
minimap, v4.5.0
script, v2.18.0
vim-mode, v0.37.0

# Dev
No dev packages
```

**Comment by tkw1536** [comment]
@martin0258 Sames as #32, what does this have to do with the atom-terminal package?

The error traces into the minimap package (NOT atom-terminal): 
```
  at HTMLDivElement.<anonymous> (C:\Users\Martin\.atom\packages\minimap\lib\minimap-element.coffee:175:11)
```
