### ISSUE TITLE
Failed to activate the atom-terminal package

### ISSUE THREAD

**Issue by mohitNarang** [karan/atom-terminal#36]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-terminal](https://github.com/karan/atom-terminal) package, v0.7.0

### Stack Trace

Failed to activate the atom-terminal package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/mohitnarang/.atom/packages/atom-terminal/lib/atom-terminal.coffee:45:28)
  at Package.module.exports.Package.activateNow (/Users/mohitnarang/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
  at /Users/mohitnarang/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
  at Package.module.exports.Package.measure (/Users/mohitnarang/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.activate (/Users/mohitnarang/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Users/mohitnarang/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
  at /Users/mohitnarang/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:234:29
  at exit (/Users/mohitnarang/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Users/mohitnarang/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Users/mohitnarang/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:85:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -0:19.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-terminal, v0.7.0
javascript-snippets, v1.0.0
language-javascript-better, v1.4.0
turbo-javascript, v0.0.8

# Dev
No dev packages
```

**Comment by muhammad-ammar** [comment]
any fix to this issue?

**Comment by yurivish** [comment]
I'm encountering this too. Saw it on 10.11, and still seeing it on macOS 10.12.
